### ISSUE TITLE
Avoid selecing 1 space when encountering block comments

### ISSUE THREAD

**Issue by varemenos** [JunoLab/atom-indent-detective#2]
There are cases where the first thing entered in the file is a block comment. For example:

``` js
/**
 * UserController
 *
 * @description :: Server-side logic for managing users
 * @help        :: See http://sailsjs.org/#!/documentation/concepts/Controllers
 */

if (true) {
    console.log(false);
}
```

Note that this block comment has 1 space indentation (it's a fairly common practice). This makes indent-detective to actually set the indentation length to 1 which is incorrect.

**Comment by one-more-minute** [comment]
There are a couple of ways I can see around this:

* Wait for Atom's syntax highlighter to run, then use the parsing information to check for comments and ignore them.
* Have a heuristic which ignores lines starting with common comment characters, like `*`.

I'm not sure how worthwhile that would be, especially because this seems unlikely to come up in practice – e.g. if your example file has just one extra code block it should be properly recognised. I'm happy to take a PR if anyone wants to take it on, though.
